In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [4]:
#読み込み
train = pd.read_csv('/gifts.csv');
test = pd.read_csv('/sample_submission.csv');

# Pandasのhead()を使うと、データの最上部5段がデフォルトで表示できる
train.head()

    GiftId
0  horse_0
1  horse_1
2  horse_2
3  horse_3
4  horse_4

In [5]:
test.head()

                                               Gifts
0  horse_0 horse_1 horse_2 horse_3 horse_4 horse_...
1  horse_10 horse_11 horse_12 horse_13 horse_14 h...
2  horse_20 horse_21 horse_22 horse_23 horse_24 h...
3  horse_30 horse_31 horse_32 horse_33 horse_34 h...
4  horse_40 horse_41 horse_42 horse_43 horse_44 h...

In [6]:
# 統計情報とサイズを確認
train_shape = train.shape
test_shape = test.shape

# train:7166情報、testは716の情報
print(train_shape)
print(test_shape)

(7166, 1)
(716, 1)

In [7]:
# pandasのdescribe()を使って、各データセットの基本統計量を確認する
# countを見ると、7166なので欠損データはない
train.describe()

         GiftId
count      7166
unique     7166
top     horse_0
freq          1

In [8]:
test.describe()

                                                    Gifts
count                                                 716
unique                                                716
top     horse_0 horse_1 horse_2 horse_3 horse_4 horse_...
freq                                                    1